apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bbhorty-front-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "bbhorty-front-ip"
spec:
  rules:
    - host: bbhorty.ml
      http:
        paths:
          - path: /*
            backend:
              serviceName: front-service
              servicePort: 3000