apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horty-front
  namespace: bbhorty
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: horty-front
  targetCPUUtilizationPercentage: 80
